name = "a0b_atsam3x8e_selftest"
description = "A0B ATSAM3X8E sefltest"
version = "0.1.0-dev"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"

project-files = ["a0b_atsam3x8e_selftest.gpr"]

[configuration]
generate_ada = false
generate_c = false
generate_gpr = true

[configuration.values]
a0b_armv7m.fpu_extension = "none"

[[depends-on]]
a0b_atsam3x8e = "*"

[[pins]]
a0b_atsam3x8e = { path='..' }
