name = "a0b_atsam3x8e"
description = "A0B ATSAM3X8E MCU Support"
version = "0.1.0-dev"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["embedded", "atsam3x8e", "sam3x8e", "arduino", "due", "svd"]

project-files = ["gnat/a0b_atsam3x8e.gpr"]

[configuration]
disabled = true

[configuration.values]
a0b_armv7m.fpu_extension = "none"

[[depends-on]]
a0b_base = "*"
a0b_armv7m = "*"
gnat_arm_elf = "*"
